<?php
/*
 *
 * (c) Nicolas Cuevas <nicolasgcuevas@gmail.com>
 *
 */

namespace AppParking\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use AppParking\Entity\UserAudit;
use AppParking\Entity\User;
use AppParking\Repository\Reusable\AttributesTrait;
use Exception;
use DateTime;

/**
 * UserAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAuditRepository extends EntityRepository
{
    use AttributesTrait;

    public function findById($id, $returnArray = TRUE)
    {   
        $result = NULL;
        $dql = "SELECT u, us, g  FROM AppParking\Entity\UserAudit u ".
               "JOIN u.user us ".
               "JOIN us.userGroups g ".
               "WHERE u.id = '".$id."'";
        try{
            if($returnArray){
                $result = $this->getEntityManager()->createQuery($dql)->getArrayResult();
            }else{
                $result = $this->getEntityManager()->createQuery($dql)->getSingleResult();
            }
            
        }catch(NoResultException $e){
            $result = ['error'=>$e->getMessage()];
        }

        return $result;
    }

    public function findAllObjects($queryFilters)
    {   
        $result = NULL;
        $page = $queryFilters['page'];
        $limit = $queryFilters['limit'];
        $where = $queryFilters['where'];
        $orderBy = $queryFilters['orderBy'];

        $qb = $this->getEntityManager()->createQueryBuilder();
        try{
            $qb->select(array('u','us','g'))
               ->from('AppParking\Entity\UserAudit', 'u')
               ->join('u.user', 'us')
               ->join('us.userGroups', 'g')
               ->setFirstResult( ($limit * ($page)) )
               ->setMaxResults( $limit );

            if($where){
                $qb->add('where','u.'.$where['field']." LIKE '%".$where['value']."%'");
            }

            if($orderBy){
                $qb->add('orderBy','u.'.$orderBy['field'].' '.$orderBy['type']);
            }

            $query = $qb->getQuery();
            $result['items'] = $query->getArrayResult();
            $pagination = $this->getPagination($query, $page, $limit);
            $result['pagination'] = $pagination;
        }catch(NoResultException $e){
            $result = ['error'=>$e->getMessage()];
        }

        return $result;
    }

    public function create($data)
    {   
        $result = NULL;
        $em = $this->getEntityManager();
        try{
            $obj = new UserAudit();
            /*$obj->setName($data['name']);
            $obj->setDescription($data['description']);
            $obj->setShortName($data['shortName']);
            $obj->setSymbol($data['symbol']);*/
            $em->persist($obj);
            $em->flush();
        }catch(Exception $e){
            $result = ['error'=>$e->getMessage()];
        }

        return $result;
    }
    
    public function createSimpleAudit($userId,$action,$meta=NULL)
    {   
        $result = FALSE;
        $em = $this->getEntityManager();
        try{            
            $user = $em->getRepository('AppParking\Entity\User')
                              ->find($userId);
            $obj = new UserAudit();
            $obj->setAction($action);
            $obj->setMeta($meta);
            $obj->setUser($user);
            $em->persist($obj);
            $user->addAudit($obj);
            $em->persist($obj);
            $em->flush();
            $result = TRUE;
        }catch(Exception $e){
            // Do nothing
        }
        return $result;
    }

    public function update($id, $data)
    {   
        $result = NULL;
        $em = $this->getEntityManager();
        try{
            $obj = $this->findById($id,FALSE);
            if(is_object($obj)){
                /*if(isset($data['name'])){
                    $obj->setName($data['name']);
                }
                if(isset($data['description'])){
                    $obj->setDescription($data['description']);
                }
                if(isset($data['shortName'])){
                    $obj->setShortName($data['shortName']);
                }
                if(isset($data['symbol'])){
                    $obj->setSymbol($data['symbol']);
                }*/
                $em->persist($obj);
                $em->flush();
            }
        }catch(Exception $e){
            $result = ['error'=>$e->getMessage()];
        }

        return $result;
    }
}