<?php
/*
 *
 * (c) Nicolas Cuevas <nicolasgcuevas@gmail.com>
 *
 */

namespace AppParking\Repository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGroups($page=NULL,$limit=NULL,$orderBy=NULL)
    {   $result = NULL;

        $qb = $this->getEntityManager()->createQueryBuilder();
        try{
            $qb->select(array('g'))
               ->from('AppParking\Entity\UserGroup', 'g');
            $query = $qb->getQuery();
            $result = $query->getArrayResult();
        }catch(NoResultException $e){
            $result = NULL;
        }

        return $result;
    }
}
